// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: item.sql

package database

import (
	"context"
)

const createItem = `-- name: CreateItem :exec
INSERT INTO Items (
        Classid,
        ItemName,
        ImageUrl,
        DayChange,
        WeekChange
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING classid, itemname, daychange, weekchange, imageurl
`

type CreateItemParams struct {
	Classid    string
	Itemname   string
	Imageurl   string
	Daychange  float64
	Weekchange float64
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) error {
	_, err := q.db.ExecContext(ctx, createItem,
		arg.Classid,
		arg.Itemname,
		arg.Imageurl,
		arg.Daychange,
		arg.Weekchange,
	)
	return err
}

const updatePriceChange = `-- name: UpdatePriceChange :exec
UPDATE Items
SET DayChange = $1,
    WeekChange = $2
WHERE Classid = $3
`

type UpdatePriceChangeParams struct {
	Daychange  float64
	Weekchange float64
	Classid    string
}

func (q *Queries) UpdatePriceChange(ctx context.Context, arg UpdatePriceChangeParams) error {
	_, err := q.db.ExecContext(ctx, updatePriceChange, arg.Daychange, arg.Weekchange, arg.Classid)
	return err
}
