// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type Item struct {
	Classid    string
	Itemname   string
	Daychange  float64
	Weekchange float64
	Imageurl   string
}

type Price struct {
	Pricedate time.Time
	ItemID    string
	Price     float64
}
